package playbook

import (
	"fmt"
	"reflect"
	"strings"
	"testing"
)

// The reference table in parsekv_reference_test.go was generated by
// running real's own parse_kv over each input. This runs ours over the
// same inputs and demands the same answers.
func TestParseKVAgainstReal(t *testing.T) {
	for _, tc := range parseKVReference {
		t.Run(tc.name, func(t *testing.T) {
			for _, mode := range []struct {
				checkRaw bool
				want     map[string]any
				label    string
			}{
				{false, tc.kv, "checkRaw=false"},
				{true, tc.raw, "checkRaw=true"},
			} {
				got, err := parseKV(tc.in, mode.checkRaw)
				if tc.kvErr {
					if err == nil {
						t.Errorf("%s: %q accepted; real raises AnsibleParserError", mode.label, tc.in)
					}
					continue
				}
				if err != nil {
					t.Errorf("%s: %q: %v", mode.label, tc.in, err)
					continue
				}
				if !reflect.DeepEqual(got, mode.want) {
					t.Errorf("%s: %q\n got %#v\nwant %#v", mode.label, tc.in, got, mode.want)
				}
			}
		})
	}
}

func TestParseKVUnbalancedQuoteIsAnError(t *testing.T) {
	// Real raises rather than guessing where the string ended, and the
	// message names the offending argument string.
	if _, err := parseKV(`msg="unterminated`, false); err == nil {
		t.Fatal("accepted an unterminated quote")
	}
	if _, err := splitArgs(`{{ unbalanced`); err == nil {
		t.Error("accepted an unbalanced jinja block")
	}
}

func TestUnquoteOnlyStripsAMatchingPair(t *testing.T) {
	for in, want := range map[string]string{
		`"a"`: "a", `'a'`: "a", `"a`: `"a`, `a"`: `a"`,
		`"a'`: `"a'`, `""`: "", `"`: `"`, ``: ``,
		// Measured: a pair whose closing quote is itself preceded by a
		// backslash IS stripped, because is_quoted looks at the
		// second-to-LAST character -- here the escaped quote, not the
		// backslash. It is the unpaired form below that survives whole.
		`"a\""`: `a\"`,
		`"a\"`:  `"a\"`,
	} {
		if got := unquote(in); got != want {
			t.Errorf("unquote(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestDecodeEscapesLeavesAnEscapedEqualsAlone(t *testing.T) {
	// This is the reason `k=a\=b` keeps its backslash: `\=` is not one
	// of the sequences real's regex recognises, so nothing rewrites it.
	if got := decodeEscapes(`a\=b`); got != `a\=b` {
		t.Errorf("decodeEscapes(%q) = %q, want it unchanged", `a\=b`, got)
	}
	for in, want := range map[string]string{
		`a\nb`:      "a\nb",
		`a\tb`:      "a\tb",
		`a\\b`:      `a\b`,
		`a\x41b`:    "aAb",
		`aAb`:       "aAb",
		`a\101b`:    "aAb",
		`a\qb`:      `a\qb`,
		`trailing\`: `trailing\`,
	} {
		if got := decodeEscapes(in); got != want {
			t.Errorf("decodeEscapes(%q) = %q, want %q", in, got, want)
		}
	}
}

// The two places a k=v string reaches a task: after the module key, and
// after action:/local_action:. Both used to take the whole string as
// _raw_params, so `debug: msg=x` printed debug's default message.
func TestTaskParsesKeyValueArguments(t *testing.T) {
	for _, tc := range []struct {
		name, yaml string
		module     string
		want       map[string]any
	}{
		{"module key", "- debug: msg=\"kv form\"\n", "debug",
			map[string]any{"msg": "kv form"}},
		{"module key two options", "- file: path=/tmp/x state=touch\n", "file",
			map[string]any{"path": "/tmp/x", "state": "touch"}},
		{"action", "- action: debug msg=\"from action\"\n", "debug",
			map[string]any{"msg": "from action"}},
		{"local_action", "- local_action: debug msg=\"from local\"\n", "debug",
			map[string]any{"msg": "from local"}},
		// A freeform action keeps its command line, and still reads the
		// few options the command family understands.
		{"command stays raw", "- command: echo a=b\n", "command",
			map[string]any{"_raw_params": "echo a=b"}},
		{"command with chdir", "- command: chdir=/tmp echo hi\n", "command",
			map[string]any{"_raw_params": "echo hi", "chdir": "/tmp"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			tasks, err := parseTasksYAML(t, tc.yaml)
			if err != nil {
				t.Fatalf("parsing: %v", err)
			}
			if len(tasks) != 1 {
				t.Fatalf("got %d tasks, want 1", len(tasks))
			}
			if tasks[0].Module != tc.module {
				t.Errorf("module = %q, want %q", tasks[0].Module, tc.module)
			}
			if !reflect.DeepEqual(tasks[0].Args, tc.want) {
				t.Errorf("args = %#v, want %#v", tasks[0].Args, tc.want)
			}
		})
	}
}

func TestTaskRejectsRawParamsForAModuleThatCannotTakeThem(t *testing.T) {
	// Real: Action 'ansible.builtin.debug' does not support raw params.
	// Silently dropping them made `debug: hello there` print debug's
	// default message where real stops the play.
	if _, err := parseTasksYAML(t, "- debug: hello there\n"); err == nil {
		t.Error("accepted raw params for debug")
	}
	// set_fact is on real's RAW_PARAM_MODULES, so it may have them.
	if _, err := parseTasksYAML(t, "- set_fact: myvar=fromkv\n"); err != nil {
		t.Errorf("set_fact k=v rejected: %v", err)
	}
}

// parseTasksYAML parses a task list by wrapping it in the smallest
// playbook that will hold one, so these tests go through the same Parse
// a real playbook does rather than calling the argument parser directly.
func parseTasksYAML(t *testing.T, tasks string) ([]Task, error) {
	t.Helper()
	var indented strings.Builder
	for _, line := range strings.Split(strings.TrimRight(tasks, "\n"), "\n") {
		indented.WriteString("    " + line + "\n")
	}
	pb, err := Parse([]byte("- hosts: all\n  gather_facts: false\n  tasks:\n" + indented.String()))
	if err != nil {
		return nil, err
	}
	if len(pb) != 1 {
		return nil, fmt.Errorf("got %d plays, want 1", len(pb))
	}
	return pb[0].Tasks, nil
}
