package playbook

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/go-ansible/vars"
)

// The reference table in parsekv_reference_test.go was generated by
// running real's own parse_kv over each input. This runs ours over the
// same inputs and demands the same answers.
func TestParseKVAgainstReal(t *testing.T) {
	for _, tc := range parseKVReference {
		t.Run(tc.name, func(t *testing.T) {
			for _, mode := range []struct {
				checkRaw bool
				want     map[string]any
				label    string
			}{
				{false, tc.kv, "checkRaw=false"},
				{true, tc.raw, "checkRaw=true"},
			} {
				got, err := parseKV(tc.in, mode.checkRaw)
				if tc.kvErr {
					if err == nil {
						t.Errorf("%s: %q accepted; real raises AnsibleParserError", mode.label, tc.in)
					}
					continue
				}
				if err != nil {
					t.Errorf("%s: %q: %v", mode.label, tc.in, err)
					continue
				}
				if !reflect.DeepEqual(got, mode.want) {
					t.Errorf("%s: %q\n got %#v\nwant %#v", mode.label, tc.in, got, mode.want)
				}
			}
		})
	}
}

func TestParseKVUnbalancedQuoteIsAnError(t *testing.T) {
	// Real raises rather than guessing where the string ended, and the
	// message names the offending argument string.
	if _, err := parseKV(`msg="unterminated`, false); err == nil {
		t.Fatal("accepted an unterminated quote")
	}
	if _, err := splitArgs(`{{ unbalanced`); err == nil {
		t.Error("accepted an unbalanced jinja block")
	}
}

func TestUnquoteOnlyStripsAMatchingPair(t *testing.T) {
	for in, want := range map[string]string{
		`"a"`: "a", `'a'`: "a", `"a`: `"a`, `a"`: `a"`,
		`"a'`: `"a'`, `""`: "", `"`: `"`, ``: ``,
		// Measured: a pair whose closing quote is itself preceded by a
		// backslash IS stripped, because is_quoted looks at the
		// second-to-LAST character -- here the escaped quote, not the
		// backslash. It is the unpaired form below that survives whole.
		`"a\""`: `a\"`,
		`"a\"`:  `"a\"`,
	} {
		if got := unquote(in); got != want {
			t.Errorf("unquote(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestDecodeEscapesLeavesAnEscapedEqualsAlone(t *testing.T) {
	// This is the reason `k=a\=b` keeps its backslash: `\=` is not one
	// of the sequences real's regex recognises, so nothing rewrites it.
	if got := decodeEscapes(`a\=b`); got != `a\=b` {
		t.Errorf("decodeEscapes(%q) = %q, want it unchanged", `a\=b`, got)
	}
	for in, want := range map[string]string{
		`a\nb`:      "a\nb",
		`a\tb`:      "a\tb",
		`a\\b`:      `a\b`,
		`a\x41b`:    "aAb",
		`aAb`:       "aAb",
		`a\101b`:    "aAb",
		`a\qb`:      `a\qb`,
		`trailing\`: `trailing\`,
	} {
		if got := decodeEscapes(in); got != want {
			t.Errorf("decodeEscapes(%q) = %q, want %q", in, got, want)
		}
	}
}

// The two places a k=v string reaches a task: after the module key, and
// after action:/local_action:. Both used to take the whole string as
// _raw_params, so `debug: msg=x` printed debug's default message.
func TestTaskParsesKeyValueArguments(t *testing.T) {
	for _, tc := range []struct {
		name, yaml string
		module     string
		want       map[string]any
	}{
		{"module key", "- debug: msg=\"kv form\"\n", "debug",
			map[string]any{"msg": "kv form"}},
		{"module key two options", "- file: path=/tmp/x state=touch\n", "file",
			map[string]any{"path": "/tmp/x", "state": "touch"}},
		{"action", "- action: debug msg=\"from action\"\n", "debug",
			map[string]any{"msg": "from action"}},
		{"local_action", "- local_action: debug msg=\"from local\"\n", "debug",
			map[string]any{"msg": "from local"}},
		// A freeform action keeps its command line, and still reads the
		// few options the command family understands.
		{"command stays raw", "- command: echo a=b\n", "command",
			map[string]any{"_raw_params": "echo a=b"}},
		{"command with chdir", "- command: chdir=/tmp echo hi\n", "command",
			map[string]any{"_raw_params": "echo hi", "chdir": "/tmp"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			tasks, err := parseTasksYAML(t, tc.yaml)
			if err != nil {
				t.Fatalf("parsing: %v", err)
			}
			if len(tasks) != 1 {
				t.Fatalf("got %d tasks, want 1", len(tasks))
			}
			if tasks[0].Module != tc.module {
				t.Errorf("module = %q, want %q", tasks[0].Module, tc.module)
			}
			if !reflect.DeepEqual(tasks[0].Args, tc.want) {
				t.Errorf("args = %#v, want %#v", tasks[0].Args, tc.want)
			}
		})
	}
}

func TestTaskRecordsRawParamsRefusalForTheRun(t *testing.T) {
	// Real raises this when the TASK RUNS, not while parsing: a
	// playbook holding such a task parses fine and its earlier tasks
	// still run. So parsing records the message and the engine raises
	// it -- see TestRawParamsFailsTheTaskNotTheParse.
	tasks, err := parseTasksYAML(t, "- debug: hello there\n")
	if err != nil {
		t.Fatalf("parsing rejected the playbook: %v", err)
	}
	want := "Action 'ansible.builtin.debug' does not support raw params."
	if tasks[0].ArgsError != want {
		t.Errorf("ArgsError = %q, want %q", tasks[0].ArgsError, want)
	}
	// The action: form records the same refusal.
	tasks, err = parseTasksYAML(t, "- action: debug hello there\n")
	if err != nil {
		t.Fatalf("parsing rejected the action form: %v", err)
	}
	if tasks[0].ArgsError != want {
		t.Errorf("action ArgsError = %q, want %q", tasks[0].ArgsError, want)
	}
	// set_fact is on real's RAW_PARAM_MODULES, so it may have them.
	tasks, err = parseTasksYAML(t, "- set_fact: myvar=fromkv\n")
	if err != nil {
		t.Fatalf("set_fact k=v rejected: %v", err)
	}
	if tasks[0].ArgsError != "" {
		t.Errorf("set_fact refused: %q", tasks[0].ArgsError)
	}
	// And a module that legitimately has none records nothing.
	tasks, err = parseTasksYAML(t, "- debug: msg=fine\n")
	if err != nil {
		t.Fatal(err)
	}
	if tasks[0].ArgsError != "" {
		t.Errorf("a clean k=v task was refused: %q", tasks[0].ArgsError)
	}
}

// parseTasksYAML parses a task list by wrapping it in the smallest
// playbook that will hold one, so these tests go through the same Parse
// a real playbook does rather than calling the argument parser directly.
func parseTasksYAML(t *testing.T, tasks string) ([]Task, error) {
	t.Helper()
	var indented strings.Builder
	for _, line := range strings.Split(strings.TrimRight(tasks, "\n"), "\n") {
		indented.WriteString("    " + line + "\n")
	}
	pb, err := Parse([]byte("- hosts: all\n  gather_facts: false\n  tasks:\n" + indented.String()))
	if err != nil {
		return nil, err
	}
	if len(pb) != 1 {
		return nil, fmt.Errorf("got %d plays, want 1", len(pb))
	}
	return pb[0].Tasks, nil
}

// The search path the engine hands each task. Measured from real:
// a role task sees [<role>, <role>/tasks, <playbook_dir>] and a play
// task sees [<playbook_dir>]. The working directory is on neither.
func TestSearchPathForRoleAndPlayTasks(t *testing.T) {
	vc := vars.New()
	vc.SetVar(vars.Inventory, "playbook_dir", "/pb")

	if got := searchPath(Task{}, vc); len(got) != 1 || got[0] != "/pb" {
		t.Errorf("play task search path = %v, want [/pb]", got)
	}
	got := searchPath(Task{RoleDir: "/pb/roles/r1"}, vc)
	want := []any{"/pb/roles/r1", "/pb/roles/r1/tasks", "/pb"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("role task search path = %v, want %v", got, want)
	}
	// No playbook_dir at all (a playbook parsed from bytes) leaves the
	// role entries alone rather than adding an empty directory, which
	// would resolve every relative name against the filesystem root.
	empty := vars.New()
	if got := searchPath(Task{}, empty); len(got) != 0 {
		t.Errorf("search path without playbook_dir = %v, want empty", got)
	}
}

// The ordering, measured from real: a playbook holding a raw-params
// refusal still parses, the tasks BEFORE it run, one with when: false
// is SKIPPED rather than failed, the live one fails, and ignore_errors
// lets the play carry on.
func TestRawParamsFailsTheTaskNotTheParse(t *testing.T) {
	pb, err := Parse([]byte(`
- name: raw params ordering
  hosts: all
  gather_facts: false
  tasks:
    - name: before
      debug: msg=ok
    - name: skipped raw params
      debug: hello there
      when: false
    - name: live raw params
      debug: hello there
      ignore_errors: true
    - name: after
      debug: msg=end
`))
	if err != nil {
		t.Fatalf("the playbook did not parse: %v", err)
	}

	var got []Result
	e := New(localhostInventory())
	e.OnResult = func(r Result) { got = append(got, r) }
	if _, err := e.RunPlaybook(context.Background(), pb); err != nil {
		t.Fatal(err)
	}

	if len(got) != 4 {
		t.Fatalf("got %d results, want 4: %+v", len(got), got)
	}
	if got[0].Failed || got[0].Skipped {
		t.Errorf("the task before the refusal did not run: %+v", got[0])
	}
	if !got[1].Skipped || got[1].Failed {
		t.Errorf("when: false did not skip the refusal: %+v", got[1])
	}
	if !got[2].Failed {
		t.Errorf("the live refusal did not fail: %+v", got[2])
	}
	want := "Task failed: Action 'ansible.builtin.debug' does not support raw params."
	if got[2].Msg != want {
		t.Errorf("msg = %q, want %q", got[2].Msg, want)
	}
	// ignore_errors let the play reach the last task.
	if got[3].Failed || got[3].Skipped {
		t.Errorf("the play stopped at the refusal: %+v", got[3])
	}
}

// A strict lookup failure reaches the user as real words it, with none
// of gonja's own call-stack prose in front. Measured from real:
//
//	Task failed: Finalization of task args for 'ansible.builtin.debug'
//	failed: Error while resolving value for 'msg': The lookup plugin
//	'file' failed: Unable to access the file 'nope.txt': File not
//	found. Use -vvvvv to see paths searched.
func TestLookupFailureReachesTheUserAsRealWordsIt(t *testing.T) {
	pb, err := Parse([]byte(`
- hosts: all
  gather_facts: false
  tasks:
    - debug:
        msg: "{{ lookup('file', 'definitely-not-here.txt') }}"
`))
	if err != nil {
		t.Fatal(err)
	}
	var got []Result
	e := New(localhostInventory())
	e.OnResult = func(r Result) { got = append(got, r) }
	if _, err := e.RunPlaybook(context.Background(), pb); err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 || !got[0].Failed {
		t.Fatalf("want one failed result, got %+v", got)
	}
	want := "Task failed: Finalization of task args for 'ansible.builtin.debug' failed: " +
		"Error while resolving value for 'msg': The lookup plugin 'file' failed: " +
		"Unable to access the file 'definitely-not-here.txt': File not found. " +
		"Use -vvvvv to see paths searched."
	if got[0].Msg != want {
		t.Errorf("msg  = %q\nwant = %q", got[0].Msg, want)
	}
}

// A relative local source resolves through the task's search path, with
// the module's own subdirectory tried before the directory itself.
// Measured from real with the same filename in every layer at once:
// copy and script take files/, template takes templates/, the role
// comes before the playbook, and remote_src is not resolved here at all.
func TestResolveLocalSrc(t *testing.T) {
	root := t.TempDir()
	role := filepath.Join(root, "roles", "r1")
	pb := filepath.Join(root, "pb")
	for _, d := range []string{
		filepath.Join(role, "files"), filepath.Join(role, "templates"),
		filepath.Join(pb, "files"), filepath.Join(pb, "templates"),
	} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	touch := func(parts ...string) string {
		p := filepath.Join(parts...)
		if err := os.WriteFile(p, []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
		return p
	}
	roleFiles := touch(role, "files", "s.txt")
	pbFiles := touch(pb, "files", "s.txt")
	pbTemplates := touch(pb, "templates", "s.j2")
	pbBare := touch(pb, "bare.txt")
	// The SAME name in both layers of one directory: the only shape
	// that tells "subdirectory first" apart from "directory first".
	// Without it the two orders are the same function, and a neuter
	// swapping them passed.
	bothSub := touch(pb, "files", "both.txt")
	touch(pb, "both.txt")

	playDirs := []string{pb}
	roleDirs := []string{role, filepath.Join(role, "tasks"), pb}

	for _, tc := range []struct {
		name string
		task Task
		args map[string]any
		dirs []string
		key  string
		want any
	}{
		{"play copy finds files/", Task{Module: "copy"},
			map[string]any{"src": "s.txt"}, playDirs, "src", pbFiles},
		{"role copy prefers its own", Task{Module: "copy", RoleDir: role},
			map[string]any{"src": "s.txt"}, roleDirs, "src", roleFiles},
		{"template takes templates/", Task{Module: "template"},
			map[string]any{"src": "s.j2"}, playDirs, "src", pbTemplates},
		{"bare directory is searched too", Task{Module: "copy"},
			map[string]any{"src": "bare.txt"}, playDirs, "src", pbBare},
		{"the subdirectory wins over the directory", Task{Module: "copy"},
			map[string]any{"src": "both.txt"}, playDirs, "src", bothSub},
		{"script resolves its first word", Task{Module: "script"},
			map[string]any{"_raw_params": "s.txt one two"}, playDirs,
			"_raw_params", pbFiles + " one two"},
		// Left alone, each for its own reason.
		{"absolute src untouched", Task{Module: "copy"},
			map[string]any{"src": "/etc/hosts"}, playDirs, "src", "/etc/hosts"},
		{"missing src untouched", Task{Module: "copy"},
			map[string]any{"src": "nowhere.txt"}, playDirs, "src", "nowhere.txt"},
		{"remote_src untouched", Task{Module: "copy"},
			map[string]any{"src": "s.txt", "remote_src": true}, playDirs, "src", "s.txt"},
		{"remote_src as a string untouched", Task{Module: "copy"},
			map[string]any{"src": "s.txt", "remote_src": "yes"}, playDirs, "src", "s.txt"},
		{"a module with no local source", Task{Module: "file"},
			map[string]any{"src": "s.txt"}, playDirs, "src", "s.txt"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resolveLocalSrc(tc.task, tc.args, tc.dirs)
			if tc.args[tc.key] != tc.want {
				t.Errorf("%s = %v, want %v", tc.key, tc.args[tc.key], tc.want)
			}
		})
	}
}
